apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vsys-ui-angular-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"

    #nginx.ingress.kubernetes.io/rewrite-target: /

spec:

  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vsys-ui-angular-service
                port:
                  number: 80
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: graph-vsys-vis-prod-service
                port:
                  number: 8080
