apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsys-ui-angular
  labels:
    app: vsys-ui-angular
spec:
  replicas: 1
  template:
    metadata:
      name: vsys-ui-angular
      labels:
        app: vsys-ui-angular
    spec:
      containers:
        - name: vsys-ui-angular
          image: registry.projectdw.de/vsys-ui-angular
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "0.20"
            limits:
              memory: "1Gi"
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
  selector:
    matchLabels:
      app: vsys-ui-angular

